### ISSUE TITLE
fix ip issues with blues women audio

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#112]
the files in the blues women ftp directory can't be hosted from omeka unless we figure out a method for excerpting them to 30 seconds.  I'd like to remove them from our servers or replace with 30 second excerpts which we can justify as fair use.  @halljt can they be swapped out for youtube audio? @damg70 can youtube be embedded in omeka like the audio files are currently?  Don't want to break this but don't want any more surprises from cybercops.  THese are fine if they are not connected anywhere in the google bot.  I will add robots.txt nofollow right now for that.

**Comment by rcrath** [comment]
robots no follow added for blues women and omeka

**Comment by damg70** [comment]
1) can chop them down to 30s playback in software
2) youtube *can* be embedded in omeka, thus opening the experience to the youtube... experience.
3) if pressed, can actually edit down to 30s.

**Comment by richrath** [comment]
Might be a job for ecasound. If I can get the backend working can @damg70
get it to work on the web like the plan for silenciah?
