### ISSUE TITLE
retire arthum/digital

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#120]
need to retire arthum digital.  this involves making sure that data that works on arthum is up and running on dahi.manoa and that no links to arthum/digital exist on dahi. only inbound link is from dean's office I think.  write dean's office to have link changed to dahi.manoa

**Comment by rcrath** [comment]
write dean's office to have link changed to dahi.manoa

**Comment by damg70** [comment]
get dean's office to change link to dahi -- janet.

**Comment by rcrath** [comment]
redirect on arthum digital and all files deleted.
