### ISSUE TITLE
plan tea for Fall

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#121]
Make plans for tea.  One can be a meeting for CorText.  I could do one on digital research workflow and tools.  What else?

**Comment by damg70** [comment]
another possibility is walking a small group of people through mjuke.

:david

**Comment by damg70** [comment]
tea #1 - scott & rod, @rcrath , week of september 7
tea #2 - cortext: puakea, karen, noelani, @rrath week of september 14
tea #3, #4, #5- category x, y, z of achievements october 12, 19, 26

**Comment by damg70** [comment]
Invites are out for #1 and #2.
#1 is being negotiated via email.
#2 is being scheduled via [Doodle](http://doodle.com/h7we2ht9x79xpdse).

**Comment by rcrath** [comment]
@damg70 update?

**Comment by rcrath** [comment]
proposing Oct. 16, 1:30 for [CorText](https://github.com/digiah/cortext) "tea" with JKaren Jolly, Noelani Arista, Puakea Nogelmeier, @damg70 @rcrath @kljolly

**Comment by rcrath** [comment]
Schedule "R" over "T"  with @rdbeales @damg70 @rcrath and a general invite.  Also maybe ask Sean from HPC to come? November

**Comment by damg70** [comment]
sent email to attendees to confirm 10/16 1:30PM meeting.

**Comment by rcrath** [comment]
Achievements Tea in November 16?
