### ISSUE TITLE
post on open access week

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#144]
Do some promotion around Open Access week on blog.

**Comment by oksveta** [comment]
@rcrath @damg70 Do you guys need any help with this? I can help write a blog post (if you don't already have something in mind).

**Comment by rcrath** [comment]
@oksveta, that will be great. @damg70 could you set sveta up with a WordPress account?

**Comment by rcrath** [comment]
@oksveta, this is coming up next week so it would be great if you could post a quick not with links to the event.  I sent you a new wordpress account email.  Let me know if you do not have time to do this by Monday (Monday is fine, son't want to eat into yr weekend) or if you have trouble logging in to wp.  @damg70 no need to set up account any more.

**Comment by oksveta** [comment]
@rcrath yup! it's at the top of my to-do list today.

**Comment by oksveta** [comment]
done: http://dahi.manoa.hawaii.edu/2015/10/oa2k15/
