### ISSUE TITLE
October 13 announcements

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#160]
FOr Sveta and David's Lunchtime DAHI session.  send announcement to 
1.  university events calendar, 
2. DAHI mailing list (maybe 2x, once a week before and once on the morning of -- also, could you put links in the email to the two most recent blog posts and the instructions for deleting one's name from the google sheet if they want to stop getting the emails.) 
3. DAHI blog

ANywhere else you want to publicize @oksveta @rdbeales ?

**Comment by oksveta** [comment]
@rcrath I can't think of anywhere else. We are co-chairing a digital projects group in the library... our first meeting is the day before so we'll share the details there as well. @rdbeales

**Comment by rcrath** [comment]
Sounds good then.
