### ISSUE TITLE
blues women audio missing

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#170]
Audio files in the text of the [Women Sing the Blues](http://dahi.manoa.hawaii.edu/omeka/exhibits/show/blueswomen) exhibit do not display for a non-logged in user.  At least one of the links is still pointing to the old server still.

**Comment by damg70** [comment]
I can understand the broken link but I think that Jeannette knows how to fix that. The issue of being logged in makes no sense tho.  Omeka diminishing in my eyes. 

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
I didn't check it logged in so not sure if looging in is a factor or not, but the site is styled differently when logged in than when not.  I want to see it as someone coming to visit without an account would though.

**Comment by damg70** [comment]
OK. 

i looked clsoely at the differences between @halljt 's ITEMS in Omeka and her EXHIBIT. the ITEMS had the correct URLs to trigger playback, but the "Am I Blue?" EXHIBITION page(s?) didn't. 

i fixed that. and i also fixed the "baby won't you please come home" pages by adding the players to the respective versions of the song. they work... as a logged in person as well. 

[blue?](http://dahi.manoa.hawaii.edu/omeka/exhibits/show/blueswomen/amiblue)
[baby](http://dahi.manoa.hawaii.edu/omeka/exhibits/show/blueswomen/babywontyoupleasecomehome)

@halljt  knows how to fix the rest... moving on to the 30s playback limit now.

**Comment by damg70** [comment]
ok. @halljt  @rcrath 30s playback limitation is now enforced. all tracks only play the first 30s... clicking beyond that point on the timeline yields a satisfying _TINY_ fragment of the audio... "blip." otherwise, you have to play from the beginning to 30s.

**Comment by richrath** [comment]
@haljit, let me know when this is fixed.  This way you can include the url
of the project in the journal article, which will greatly enhance it.  We
can close the issue once you have the fix in.

Digital Arts and Humanities Initiative http://dahi.manoa.hawaii.edu
University of Hawaiʿi at Mānoa
uhdahi@hawaii.edu

**Comment by halljt** [comment]
Hi,

Thanks for all your work here.  The players look good--i just checked them
all and the 30 seconds thing is enforced for all of them (except Bette
Midler's Drinking Again doesn't seem to be there.) I'm going to add the
players to the exhibit page as well, and I think everything is public?  (it
seems to be...)

Thanks!

On Mon, Nov 23, 2015 at 2:19 PM, richrath notifications@github.com wrote:

> @haljit, let me know when this is fixed. This way you can include the url
> of the project in the journal article, which will greatly enhance it. We
> can close the issue once you have the fix in.
> 
> Digital Arts and Humanities Initiative http://dahi.manoa.hawaii.edu
> University of Hawaiʿi at Mānoa
> uhdahi@hawaii.edu
> 
> On Mon, Nov 23, 2015 at 12:30 PM damg70 notifications@github.com wrote:
> 
> > ok. @halljt https://github.com/halljt @rcrath
> > https://github.com/rcrath 30s playback limitation is now enforced. all
> > tracks only play the first 30s... clicking beyond that point on the
> > timeline yields a satisfying _TINY_ fragment of the audio... "blip."
> > otherwise, you have to play from the beginning to 30s.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/digiah/2do/issues/170#issuecomment-159088430.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/digiah/2do/issues/170#issuecomment-159111737.

## 

Editorial Staff, _American Quarterly_
Ph.D. Candidate in American Studies
University of Hawai'i at Mānoa
2530 Dole Street, Sakamaki Hall
Honolulu, HI 96822
halljt@hawaii.edu myoshiha@hawaii.edu

**Comment by rcrath** [comment]
@halljt , it is available publicly, but only if you know where it is.  As far as I can tell, there are no links to it, so it is not in any of the search engines yet.  Is that ok?  THat way people can use it if you show it to them without getting an account and all.  Let me know when everything is in order and I will close this ticket then.  Iwas not clear from the above if it is good to go yet.

**Comment by halljt** [comment]
Ahh ok, I see.  Yes, I do need some time to clean things up.  Will let you
know.  Thanks!

On Mon, Nov 23, 2015 at 3:32 PM, Rich Rath notifications@github.com wrote:

> @halljt https://github.com/halljt , it is available publicly, but only
> if you know where it is. As far as I can tell, there are no links to it, so
> it is not in any of the search engines yet. Is that ok? THat way people can
> use it if you show it to them without getting an account and all. Let me
> know when everything is in order and I will close this ticket then. Iwas
> not clear from the above if it is good to go yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/digiah/2do/issues/170#issuecomment-159123382.

## 

Editorial Staff, _American Quarterly_
Ph.D. Candidate in American Studies
University of Hawai'i at Mānoa
2530 Dole Street, Sakamaki Hall
Honolulu, HI 96822
halljt@hawaii.edu myoshiha@hawaii.edu

**Comment by rcrath** [comment]
@haljit, just a reminder on the audio...plz put it on yr after the semester list of things 2 do!

**Comment by halljt** [comment]
got it--it's on the list!

On Wed, Dec 9, 2015 at 5:14 PM, Rich Rath notifications@github.com wrote:

> @haljit, just a reminder on the audio...plz put it on yr after the
> semester list of things 2 do!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/digiah/2do/issues/170#issuecomment-163472301.

## 

Editorial Staff, _American Quarterly_
Ph.D. Candidate in American Studies
University of Hawai'i at Mānoa
2530 Dole Street, Sakamaki Hall
Honolulu, HI 96822
halljt@hawaii.edu myoshiha@hawaii.edu

**Comment by damg70** [comment]
Just checking to see if we got this resolved. We all want the joy of CLOSING this issue.

**Comment by rcrath** [comment]
@haljit, Any update on this?  David is eyeing up the CLOSE button!

**Comment by rcrath** [comment]
@halljt I am closing this.  If it is still a problem, just reopen.
