### ISSUE TITLE
Commons Gallery Online Catalog

### ISSUE THREAD

**Issue by damg70** [digiah/2do#176]
This is the inaugrual issue...
1. Brandon Ng has set up his github account
2. Has met with David Goldberg to discuss strategy
3. Will be meeting soon

**Comment by rcrath** [comment]
duplicate of #167 ?  please consolidate.

**Comment by rcrath** [comment]
@damg70 update on this? wondering if this can be combined with [collective access project](#190)?

**Comment by rcrath** [comment]
@damg70 I accidentally deleted Brandon from the team...sent a new invite to @brandonng, who I think is the wrong person.  Could you get him signed back up?  Sorry B^}

**Comment by rcrath** [comment]
closing # 167.

**Comment by damg70** [comment]
Epitaph: Brandon Ng is no longer with the university.
