### ISSUE TITLE
EVENTS to add publicize

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#178]
@damg70, could you put together a blog post (or 3) publicizing these events.  SHould be copy paste all the way.  ALso please put in Dahi public calendar.Here are the subject lines from the emails.

Fwd: Workshop: Teaching Writing with Technology

Visit of Iain Kerr to UH iLab - a few days to delve into "Creativity" April 15-18
 – 
upcoming talk of possible interest to Digital A&H folks
 – 
Xiang Fan poster abstract 1

**Comment by damg70** [comment]
done.

**Comment by rcrath** [comment]
@damg70, blog done, reclose when calendar is updated plz.

**Comment by rcrath** [comment]
@damg70 I did the calendar.  closed again
