### ISSUE TITLE
Dahi Google Calendar iframe broken

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#179]
THe calendar at http://dahi.manoa.hawaii.edu/dahi-calendar/ is broken.  Maybe WP auto-update broke iframes support?

```
<iframe style="border-width: 0;" src="https://calendar.google.com/calendar/embed?showCalendars=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=sobq76t7vug2ce56f9u26jtp1g%40group.calendar.google.com&amp;color=%23AB8B00&amp;ctz=Pacific%2FHonolulu" width="680" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by rcrath** [comment]
@damg70 don't know if you fixed it but it seems to be back in order.  closing.

**Comment by damg70** [comment]
I fixed it with sheer outrage, staring at my screen. 

:david

I'm all thumbs over here
