### ISSUE TITLE
Import Peyten Maki's Scalar project to our server with styles intact

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#189]
Peyten Maki has an excellent [Scalar Project on the elections](http://scalar.usc.edu/works/peyten-maki-final-project-/index) but she wrote it on the USC server instead of ours.  @damg70 She already has it [imported to DAHI scalar](http://dahi.manoa.hawaii.edu/scalar/peyten-maki-final-project/index) but none of the formatting made it.  Can you see if you can restore the formatting?  This is an ASAP project, as I would like to release and publicize it before the Inauguration.  @damg70 Plz lmk whn you have gotten what you need from USC scalar site so I can unpublish Peyten's url there.

**Comment by damg70** [comment]
fixed. he had to switch the template to "scalar 2" in the dashboard.
