### ISSUE TITLE
Publicize Smile, You're Under Surveillance! events

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#191]
@damg70 plz publicize *Smile, You're Under Surveillance!* events:

- [x] blog post (link to [predictive policing](http://dahi.manoa.hawaii.edu/2017/02/predictive-policing-is-not-the-minority-report/)) video.
- [x] DAHI google calendar
- [x] email to list

**Comment by damg70** [comment]
Done.

**Comment by damg70** [comment]
I didn't put a link to the policing video because I didn't see an ego-free way to promote it. Feel free to edit the WP post if you like.

**Comment by rcrath** [comment]
Your call. I just had a week of shameless self promotion, lol. Closed.  Thnx.
