### ISSUE TITLE
Learn projects

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#195]
Explore GitHub projects as better org tool than just using issues and milestones within 2do and separate archives

**Comment by rcrath** [comment]
added to https://github.com/digiah/2do/projects/1#card-1608596

**Comment by rcrath** [comment]
@damg70 you can close this once you have a handle on projects. should take five minutes :)

**Comment by kelseykato** [comment]
Animal therapy sessions for members (fake issue) 

Everyone needs a de-stressor to help them relax once in a while, so why not bring in some cute cuddly animals to help our members de-stress?  Here are some pictures of puppies and kittens to get you excited about the idea:

![puppy_2_kbhb4a](https://cloud.githubusercontent.com/assets/22581812/22639588/cb3a3238-ebf2-11e6-93e2-7490ca81cc4c.jpg)
![kitties-cats-22092221-500-374](https://cloud.githubusercontent.com/assets/22581812/22639590/cda31882-ebf2-11e6-9a60-c8a17c744e53.jpg)
