### ISSUE TITLE
add a fake issue to the "learn Projects" project

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#196]
This will take five minutes and demonstrate you get what projects are so we can close #195.  This could be an an achievement (i.e., #134)  Once you have added it to the "[learning projects](https://github.com/digiah/2do/projects/1)" project, you can close the issue.  When all is done, we can close this and #195

**Comment by tyliec** [comment]
@rcrath #201

**Comment by rcrath** [comment]
thanks everyone.
