### ISSUE TITLE
MAPACA search refinement bug

### ISSUE THREAD

**Issue by damg70** [digiah/2do#198]
Address the doubling of the search terms when coming back from search results.
Fix that by the 23 of February.

**Comment by damg70** [comment]
co-related with edit bug... working.

**Comment by damg70** [comment]
I believe that this error was tied to the edit button not working properly... will leave this open until it is confirmed that the edit bug is fixed.

**Comment by rcrath** [comment]
Will test

**Comment by damg70** [comment]
bug fixed for dealing with ANY, EXACT, etc. content field searches. @rcrath
