### ISSUE TITLE
Get MEAN stack running

### ISSUE THREAD

**Issue by damg70** [digiah/2do#202]
I Believe @rrath is already on this.

**Comment by rcrath** [comment]
Up. Superseded by #204. Closing.

**Comment by rcrath** [comment]
I'm @rCrath,. rR is the uh name.

**Comment by rrath** [comment]
Nope, I'm not on it.

**Comment by rcrath** [comment]
@rrath, sorry for the typo...my github handle is rcrath, but my university address is rrath, so it get confusing.  Thanks for responding though!  And the demoscene Amiga thing is awesome!
