### ISSUE TITLE
Design back-end requirements (mean stack)

### ISSUE THREAD

**Issue by damg70** [digiah/2do#204]
Dr. Rath has the MEAN stack installed. Tyler needs to look it over and see if anything else is necessary to begin development.

**Comment by tyliec** [comment]
What I usually do is work on a project locally then git clone it to the server when it needs to be tested.
Can you or can I make a git repo under DAHI for us to push our work to? 
@damg70 @rcrath

**Comment by tyliec** [comment]
- Updated [npm](https://github.com/npm/npm/releases) to 4.2.0
- Installed [nvm](https://github.com/creationix/nvm)
- Used [nvm](https://github.com/creationix/nvm) to update NodeJS to [v6.9.5](https://nodejs.org/en/blog/release/v6.9.5/)

**Comment by rcrath** [comment]
You can use GitHub for repositories. We should make one for the membership project, right?  I might have to make the repo. Will do now.  I'll  also make a git project for us to organize it in.

**Comment by tyliec** [comment]
- Installed [PM2](http://pm2.keymetrics.io/)

@rcrath I can't find the github repo under https://github.com/digiah, is it somewhere else?

**Comment by tyliec** [comment]
By the way, @rcrath, do you want me asking these questions to you in Slack/Text/Github?

**Comment by rcrath** [comment]
@Viltaria if it goes off the issue topic, slack is probably better.  my bad on this one for thinking out loud and not following up.  I was not near a computer I could initiate the project on.  Doing now.  But are you pretty clear on the workflow?  Use github for keeping up to date code, but install via the ftp-then-sudo-cp method I outlined in the email to actually deploy the code on the server. Check in with David or me before deploying anything that affects projects that are already live.  setting things up now... :)

**Comment by rcrath** [comment]
@Viltaria can we close this yet, or you need to do a bit more setup and testing?

**Comment by tyliec** [comment]
I think its ready to begin deployment, I'll close the issue.

**Comment by tyliec** [comment]
@rcrath I'm assuming that we will be sitting in on the meeting tomorrow, will it be in the usual room?

**Comment by rcrath** [comment]
You are welcome if you can make it.  It would be good for you to meet Julia and take part in the process.  this would be better on slack!

**Comment by damg70** [comment]
@Viltaria has basic data pulls working. 

One can go to this URL: [http://dahi.manoa.hawaii.edu/memberconnect/test/](http://dahi.manoa.hawaii.edu/memberconnect/test/) and add a string to the end of the URL, eg [http://dahi.manoa.hawaii.edu/memberconnect/test/Richard](http://dahi.manoa.hawaii.edu/memberconnect/test/Richard) or a simple key/value pair eg [http://dahi.manoa.hawaii.edu/memberconnect/test/first_name=richard](http://dahi.manoa.hawaii.edu/memberconnect/test/first_name=richard).

The next step is to develop the means for parsing a serialized set of form elements that will be passed from the client to the server.

In the simplest case this will be a key/value pair, but the interface will make it possible to add subsequent K/V pairs separated by logical operators: AND, OR and NOT.

@Viltaria will handle unserializing these form elements and turning them into a JSON object structured so that it can be passed to db.collection.find() according to mongo syntax.

@Vilataria will handle creating a **hits { }** object that is attached to each member profile that is sent back to the client so that the browser can render emphases. For example, if <value> hits in the <first_name> field in profile 1 the matched text could be bold; if there is a photograph whose name matches <value> the browser might put an emphasized border around that image.
