### ISSUE TITLE
secure http certificate

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#21]
set up secure http.  find out how to get certificate.  need to remove current key and redo.

**Comment by rcrath** [comment]
@damg70 threat. do.

**Comment by damg70** [comment]
query submitted, cc’d @rrath

**Comment by rcrath** [comment]
:)

**Comment by rrath** [comment]
@damg70 You rang?

**Comment by rcrath** [comment]
@rrath I think @damg70 meant to ping me.

**Comment by rcrath** [comment]
http://m.slashdot.org/story/303321 Has  easy install.  What's the status @damg70 ?

**Comment by rcrath** [comment]
@damg70 see email subject "SSL for dahi.manoa.hawaii.edu" from 11/24 for this.  Get once you get caught up plz.  Let me know if u want me to do it.

**Comment by rcrath** [comment]
Completed [ITS instructions](http://www.hawaii.edu/sitelic/incommon/vm_ssl.html).  Next to do is follow [Comodo's install instructions](https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/637/37/certificate-installation-apache--mod_ssl).

**Comment by damg70** [comment]
Epitaph:

The files: right place.
The instructions: wrong rhythm. 
The fix: carefully rewording what was already in place... and getting one's own typos straight. 

:david

I'm all thumbs over here
