### ISSUE TITLE
DAHI FALL EVENTS

### ISSUE THREAD

**Issue by damg70** [digiah/2do#215]
**Tea**

1. Sent Scott email with possible dates for "Politics and Social Media" Tea... waiting to hear back from him: possible dates: **9/19** or **9/21** either **12-1 or 3-no later than 5**.

2. Reserve B213 with Sue

**Presentation Event**

1. @rcrath has contacted Julia

2. @damg70, @rcrath ... compose boilerplate invitations for: Julia (Archive of Silence), Jeannette (Blues Women), Kelsey (web site relaunch), Alex Mawyer (MIPI), Christina Higgins (Language Mapping).

3. Secure catering stuff $150 budget

4. Reserve History Library for Event

**Comment by rcrath** [comment]
@damg70 update? we can use this issue as clearinghouse.
