### ISSUE TITLE
Fall 2015 Schedule for lunch meetings

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#29]
Put together schedule for Fall 2015.

So far have asked 
* Scott Groeniger (art, emailed him) (September)
* David Beales and Sveta (October)
* Brett Oppegaard november (Comm, digital media, accepted.  here is his [title, description and bio](https://github.com/digiah/2do/blob/master/attachments/Brett%20Oppegaard%20talk.txt), as well as his [pic](https://github.com/digiah/2do/blob/master/attachments/brett%20mug%201%20copy.jpg))
* December ????

* Rod Bengston (art, emailed him) Said he cannot commit for Fall but maybe for this semester

Other things I would like to do:  Faculty asked for a session on digital materials and tenure (#30).

**Comment by damg70** [comment]
need to look at my class schedule to be sure that we don't end up in the same situation as last year.
