### ISSUE TITLE
Mapping Stadiums

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#53]
WHat is left to do here as far as code?  This will be tied in with #54 

What can Huston now do with it?

Invite Huston to Github

**Comment by rcrath** [comment]
@damg70  I changed the url in the wp entry, but the mapping folder does not work on dahi.manoa yet, so Huston's article is broken for the moment.

**Comment by damg70** [comment]
Works correctly under new domain name. Icons were updated june... should be good to go... right @phustonladner ?

**Comment by damg70** [comment]
fixed. see other closed item.
