### ISSUE TITLE
Resource database of member skills

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#61]
A database of resources of particpants for other particpants to draw on. part of [i/o](#60)

**Comment by damg70** [comment]
this needs to be something that you want to come and look at on DAHI. like if we as people to "tag" their identities ... as a kind of prototype for the "gamer" identity ... 

idea would be to draw lines between the representations of people that share tags, positioning those with greater affinities closer to each other, as well as perhaps adding a different visual indicator for "unmet needs." 

maybe each tag a member has is valued from -100 to 100, with the < 0 indicating degree of demand and > 0 indicating degree of supply. so if the tag is MUSIC, i might rate it 95... some other member might rate it -25 and the interface would render a line between us, and move our representations to an appropriate distance indicating supply and demand.

**Comment by richrath** [comment]
Sounds like the Google doc will not have this. MySQL-r-d3? Obviously we
need to keep the user maintain ability. I wonder if the new library people
are coming. One of them knows r. I like the supply demand model. There is
an old socialist maxim "from each according to their abilities, to each
according to their needs" which I like better than the capitalist version.
A possible problem with negative numbers approach is what about
complementary skills an needs? The positive/negative version would make the
strongest connections cancel out! Let's keep it all positive no? Excuse my
Pollyanna. Sounds like a vue map would clarify both visualization and
coceptualizaion. Or the whiteboard.

**Comment by rcrath** [comment]
needs to be tied in with [achievements](https://github.com/digiah/achievements)

**Comment by rcrath** [comment]
closing and moving to memberconnect project
