### ISSUE TITLE
truths project payoff

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#68]
http://dahi.manoa.hawaii.edu/truth/

once you submit you get a message that says:

    Thank you
    for your participation
    Please check back for the final outcome
    of this project near the end of 201 4.
    A | ec F Ll | | e r
    Art Student, Senior t UH Mno

which is a bit of a letdown after all that work :)

Can we open the project back up? I can ask Alec if you think it is a good idea. It ought to be setup so that if you complete it you can put one image in as a replacement for the one you like least. That way some data will accrue for the more popular pix, it will be self updating (Oakland becomes Ferguson). The second thing would be to hook the results into voyant tools (see above for link) or something that visualizes the results in an interesting way. I would toy around with this part, but I don't know where the data is.. Voyant have an api even I can use!

**Comment by damg70** [comment]
is this really still open? we've got the tag cloud thing working now. customizing the "truth" from this point is low priority.

**Comment by richrath** [comment]
I didn't think it was working on dahi.  I just copied the files over from
arthum.  needs to be checked that it is working is all I guess.  If so
close...no new stuff needed on it.  I could not find the tag cloud etc, but
I may not have spent enough time looking.  .
