### ISSUE TITLE
strengthening-museums

### ISSUE THREAD

**Issue by rcrath** [digiah/2do#84]
Noelle's project.
This project involves DAHI because David's (@damg70) programming expertise will be brought to bear. He has already participated in several meetings with stakeholders to provide consultation, and will be implementing the data input aspects of the survey during the last days of March.

**Comment by rcrath** [comment]
@damg70 update plz? what is the eta for this? can we close it?

**Comment by damg70** [comment]
will send note to noelle … see where we’re at. she may still be traveling.

:david

**Comment by damg70** [comment]
Will ping her again...
